version: 1.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
- MinSizeRel
- RelWithDebInfo
install:
- ps: >-
    mkdir build

    cd build

    cmake -G"Visual Studio 16 2019" ..
build:
  project: build/set-name-thread-test.sln
  verbosity: normal
test_script:
- pwsh: >-
    cd $Env:CONFIGURATION

    .\test.exe AUTOMATED